

services:
  flask_app:
    build: .
    container_name: flask_app
    depends_on:
      - mongodbtest
    environment:
      - MONGO_URI=mongodb://mongodbtest:27017/seniorDesignTesting  # Ensures Flask connects to MongoDB in Docker
      - FLASK_ENV=development  # Enables debug mode (for hot-reloading)
      - FLASK_RUN_EXTRA_FILES=1  # Required for detecting changes
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app  # Binds local code directory to container for live updates
      - ~/.cache/pip:/root/.cache/pip #use cache to grab libraries
    networks:
      - flask_network  # Ensures Flask can talk to MongoDB

  mongodbtest:
    image: mongo:6.0
    container_name: mongodbtest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db  # Persistent storage
    networks:
      - flask_network  # Ensures Flask and MongoDB are on the same network

volumes:
  mongo-data:  # Persistent MongoDB storage
 

networks:
  flask_network:  # Custom network for Flask and MongoDB
    driver: bridge
